#!/bin/bash

rm -rf work 
rm -rf modules
mkdir work modules

JACKSON_ANNOTATIONS_JAR=jars/jackson-annotations-2.8.10.jar
JACKSON_ANNOTATIONS=jackson.annotations

JACKSON_CORE_JAR=jars/jackson-core-2.8.10.jar
JACKSON_CORE=jackson.core

JACKSON_DATABIND_JAR=jars/jackson-databind-2.8.10.jar
JACKSON_DATABIND=jackson.databind

# ---------------------------
# generate jackson-core module

jdeps --generate-module-info work $JACKSON_CORE_JAR

# ---------------------------
# build  jackson-core module

JARPATH=$JACKSON_CORE_JAR
MOD=$JACKSON_CORE
ROOT_DIR=$PWD

# copy original jar into place
mkdir -p $ROOT_DIR/modules
cp $ROOT_DIR/$JARPATH $ROOT_DIR/modules/$MOD.jar

# extract original jar
rm -rf classes
mkdir classes
cd classes
jar xf $ROOT_DIR/$JARPATH

# compile module-info.java (generated by gen.sh)
cd $ROOT_DIR/work/$MOD
javac -p $MOD -d $ROOT_DIR/classes module-info.java

# update output jar
jar uf $ROOT_DIR/modules/$MOD.jar -C $ROOT_DIR/classes module-info.class

cd $ROOT_DIR

# ---------------------------
# generate jackson-annotations module

jdeps --generate-module-info work $JACKSON_ANNOTATIONS_JAR

# ---------------------------
# build  jackson-annotations module

JARPATH=$JACKSON_ANNOTATIONS_JAR
MOD=$JACKSON_ANNOTATIONS
ROOT_DIR=$PWD

# copy original jar into place
mkdir -p $ROOT_DIR/modules
cp $ROOT_DIR/$JARPATH $ROOT_DIR/modules/$MOD.jar

# extract original jar
rm -rf classes
mkdir classes
cd classes
jar xf $ROOT_DIR/$JARPATH

# compile module-info.java (generated by gen.sh)
cd $ROOT_DIR/work/$MOD
javac -p $MOD -d $ROOT_DIR/classes module-info.java

# update output jar
jar uf $ROOT_DIR/modules/$MOD.jar -C $ROOT_DIR/classes module-info.class

cd $ROOT_DIR

# ---------------------------
# generate jackson-databind module

jdeps --module-path $PWD/modules --add-modules jackson.annotations,jackson.core --generate-module-info work $JACKSON_DATABIND_JAR

# ---------------------------
# build  jackson-databind module

JARPATH=$JACKSON_DATABIND_JAR
MOD=$JACKSON_DATABIND
ROOT_DIR=$PWD

# copy original jar into place
mkdir -p $ROOT_DIR/modules
cp $ROOT_DIR/$JARPATH $ROOT_DIR/modules/$MOD.jar

# extract original jar
rm -rf classes
mkdir classes
cd classes
jar xf $ROOT_DIR/$JARPATH

# compile module-info.java (generated by gen.sh)
cd $ROOT_DIR/work/$MOD

javac --module-path $ROOT_DIR/modules --add-modules jackson.annotations,jackson.core -d $ROOT_DIR/classes module-info.java

# update output jar
jar uf $ROOT_DIR/modules/$MOD.jar -C $ROOT_DIR/classes module-info.class

cd $ROOT_DIR

rm -rf work classes 

echo "modular jars are in $PWD/module"

echo "Ready."
