
JARPATH=$1
MOD=$2
ROOT_DIR=$PWD

# copy original jar into place
mkdir -p $ROOT_DIR/out
cp $ROOT_DIR/$JARPATH $ROOT_DIR/out/$MOD.jar

# extract original jar
rm -rf classes
mkdir classes
cd classes
jar xf $ROOT_DIR/$JARPATH

# compile module-info.java (generated by gen.sh)
cd $ROOT_DIR/work/$MOD
javac -p $MOD -d $ROOT_DIR/classes module-info.java

# update output jar
jar uf $ROOT_DIR/out/$MOD.jar -C $ROOT_DIR/classes module-info.class

cd $ROOT_DIR
echo "Ready."
